### ISSUE TITLE
Criar a Introdução da Apresentação do Evento

### ISSUE THREAD

**Issue by soyvieira** [soyvieira/fashion-event#1]
Você deve fazer a introdução, resumo e sumário de toda a apresentação.

**Comment by tisoyvieira** [comment]
> Você deve fazer a introdução, resumo e sumário de toda a apresentação.

Ok

**Comment by tisoyvieira** [comment]
Feita a introdução

**Comment by soyvieira** [comment]
Olá. Vc criou a apresentação direto na Main. Na próxima etapa, crie uma branch e faça as devidas produções, que estarão passíveis de aprovação.

**Comment by tisoyvieira** [comment]
Ok
